### PR TITLE
added favicon to  the page

### PR DESCRIPTION
**Pull request by Deevyn9**
Signed-off-by: Divine <deevynobeten@gmail.com>

### CODE REVIEW

**Comment by Kartik9250** [comment]
Hey @Deevyn9,
Thank you for your PR.

We have tested the changes and would like to suggest some further improvements:
- remove the .vscode files for your commits and add them to gitignore
- use icon that has white background for the favicon

After these changes we can merge your PR.

**Comment by Deevyn9** [comment]
Okay, I'll work on them now

**Comment by jasmeet0915** [comment]
Hi @Deevyn9,
Thank you for such quick response. I have tested the changes and they seem fine!

I see you have added the `.vscode` to the `.gitignore` but you haven't removed it from existing commits like @Kartik9250 suggested. I think doing something like:
```bash
git rm -r --cached .vscode
```
should work. Once you do this and push your changes we will be good to go ahead with the merge!

**Comment by Deevyn9** [comment]
will do this right away

**Comment by Deevyn9** [comment]
done this, looking forward to the merge.

**Comment by jasmeet0915** [comment]
Looks fine! 
I have merged your changes to `main`. It should reflect on our website if everything goes right. 
Thank you for your contribution!

**Comment by Deevyn9** [comment]
You're welcome!

**Pull request merged**
